# Generated by Django 5.2 on 2025-04-30 19:38

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=60, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=home.models.Azienda.set_path)),
                ('codcf', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('prov', models.CharField(blank=True, max_length=40, null=True)),
                ('codfisc', models.CharField(blank=True, max_length=40, null=True)),
                ('partiva', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True)),
                ('pec', models.CharField(blank=True, max_length=40, null=True)),
                ('fax', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('resprap', models.CharField(blank=True, max_length=40, null=True)),
                ('fmemo', models.TextField(blank=True, null=True)),
                ('nome_pf', models.CharField(blank=True, max_length=40, null=True)),
                ('cogn_pf', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'azienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondizioniPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codpag', models.CharField(max_length=10, unique=True)),
                ('desc', models.CharField(blank=True, max_length=70, null=True)),
                ('rataiva', models.IntegerField(blank=True, null=True)),
                ('tiporate', models.CharField(blank=True, max_length=2, null=True)),
                ('ggscdfix', models.IntegerField(blank=True, null=True)),
                ('tipopag', models.IntegerField(blank=True, null=True)),
                ('numrate', models.IntegerField(blank=True, null=True)),
                ('gg1rata', models.IntegerField(blank=True, null=True)),
                ('ggrate', models.IntegerField(blank=True, null=True)),
                ('tiposcad', models.CharField(blank=True, max_length=3, null=True)),
                ('ggfixant', models.CharField(blank=True, max_length=3, null=True)),
                ('ggdopofm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condizionipagamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipologiaDocumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'tipologiadocumenti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipologiaLavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipologia_lavori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcf', models.CharField(blank=True, max_length=60, null=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('prov', models.CharField(blank=True, max_length=40, null=True)),
                ('codfisc', models.CharField(blank=True, max_length=40, null=True)),
                ('partiva', models.CharField(blank=True, max_length=40, null=True)),
                ('persoc', models.CharField(blank=True, choices=[('P', 'Persona'), ('S', 'Societa')], max_length=2, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True)),
                ('pec_fe', models.CharField(blank=True, max_length=40, null=True)),
                ('fax', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('fmemo', models.TextField(blank=True, null=True)),
                ('nome_pf', models.CharField(blank=True, max_length=40, null=True)),
                ('cogn_pf', models.CharField(blank=True, max_length=40, null=True)),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=2, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_cliente', to='home.azienda')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('ubicazione', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(null=True)),
                ('valore_commessa', models.FloatField(blank=True, null=True)),
                ('data_inizio_lavori', models.DateField(blank=True, null=True)),
                ('data_fine_lavori', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cantiere', to='home.cliente')),
            ],
            options={
                'db_table': 'cantiere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fornitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcf', models.CharField(blank=True, max_length=60, null=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('cap', models.CharField(blank=True, max_length=20, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('prov', models.CharField(blank=True, max_length=40, null=True)),
                ('codfisc', models.CharField(blank=True, max_length=40, null=True)),
                ('partiva', models.CharField(blank=True, max_length=40, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('persoc', models.CharField(blank=True, choices=[('P', 'Persona'), ('S', 'Societa')], max_length=2, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=40, null=True)),
                ('pec_fe', models.CharField(blank=True, max_length=40, null=True)),
                ('fax', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('resprap', models.CharField(blank=True, max_length=40, null=True)),
                ('fmemo', models.TextField(blank=True, null=True)),
                ('nome_pf', models.CharField(blank=True, max_length=40, null=True)),
                ('cogn_pf', models.CharField(blank=True, max_length=40, null=True)),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=2, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_fornitore', to='home.azienda')),
                ('codpag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pppp', to='home.condizionipagamento', to_field='codpag')),
            ],
            options={
                'db_table': 'fornitori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fatture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('n_fattura', models.CharField(blank=True, db_column='n_fattura', max_length=40, null=True)),
                ('data_fattura', models.DateField(blank=True, null=True)),
                ('importo', models.FloatField(blank=True, null=True)),
                ('pagato', models.FloatField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('fornitore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitore_fatture', to='home.fornitori')),
            ],
            options={
                'db_table': 'fatture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BancaFornitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfor', models.CharField(blank=True, max_length=20, null=True)),
                ('intestat', models.CharField(blank=True, max_length=80, null=True)),
                ('abi', models.CharField(blank=True, max_length=10, null=True)),
                ('cab', models.CharField(blank=True, max_length=10, null=True)),
                ('conto', models.CharField(blank=True, max_length=30, null=True)),
                ('cin', models.CharField(blank=True, max_length=10, null=True)),
                ('iban', models.CharField(blank=True, max_length=40, null=True)),
                ('indir', models.CharField(blank=True, max_length=60, null=True)),
                ('prov', models.CharField(blank=True, max_length=10, null=True)),
                ('swift', models.CharField(blank=True, max_length=30, null=True)),
                ('desban1', models.CharField(blank=True, max_length=40, null=True)),
                ('desban2', models.CharField(blank=True, max_length=30, null=True)),
                ('localita', models.CharField(blank=True, max_length=30, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True)),
                ('fornitore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitori_banca', to='home.fornitori')),
            ],
            options={
                'db_table': 'bancafornitori',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completato', models.BooleanField(default=False)),
                ('data_ordine', models.DateField(blank=True, null=True)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('importo', models.FloatField(blank=True, default=0.0, null=True)),
                ('damagazzino', models.BooleanField(default=False)),
                ('permagazzino', models.BooleanField(default=False)),
                ('tipologia', models.CharField(blank=True, choices=[('SE', 'Servizio'), ('MA', 'Materiale'), ('NO', 'Noleggio'), ('AL', 'Altro')], default='MA', max_length=2, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_ordine', to='home.azienda')),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_ordine', to='home.cantiere')),
                ('fornitore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornitori_ordine', to='home.fornitori')),
            ],
            options={
                'db_table': 'ordine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_impegnata', models.IntegerField(blank=True, default=0, null=True)),
                ('quantita_inarrivo', models.IntegerField(blank=True, default=0, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('quantita', models.IntegerField(blank=True, null=True)),
                ('prezzo_unitario', models.FloatField(blank=True, default=0.0, null=True)),
                ('importo_totale', models.FloatField(blank=True, default=0.0, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_magazzino', to='home.azienda')),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_magazzino', to='home.ordine')),
            ],
            options={
                'db_table': 'magazzino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('quantita', models.IntegerField(blank=True, default=0, null=True)),
                ('prezzo_unitario', models.FloatField(blank=True, default=0.0, null=True)),
                ('importo_totale', models.FloatField(blank=True, default=0.0, null=True)),
                ('ordine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_articoli', to='home.ordine')),
            ],
            options={
                'db_table': 'articoli',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40, null=True)),
                ('cognome', models.CharField(blank=True, max_length=40, null=True)),
                ('responsabile', models.BooleanField(default=False)),
                ('wage_lordo', models.FloatField(blank=True, null=True)),
                ('wage_netto', models.FloatField(blank=True, null=True)),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azienda_personale', to='home.azienda')),
                ('tipologia_lavoro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipolavoro_personale', to='home.tipologialavori')),
            ],
            options={
                'db_table': 'personale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScadenzarioFatture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo_rata', models.FloatField(blank=True, null=True)),
                ('scadenza_rata', models.DateField(blank=True, null=True)),
                ('importo_pagato', models.FloatField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('fattura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatture_scadenzario', to='home.fatture')),
            ],
            options={
                'db_table': 'scadenzariofatture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateField(auto_now_add=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to=home.models.Documenti.set_path)),
                ('caricato_da', models.CharField(blank=True, max_length=80, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_documenti', to='home.cantiere')),
                ('tipologia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipologia_documento', to='home.tipologiadocumenti')),
            ],
            options={
                'db_table': 'documenti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aziendauser', to='home.azienda')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userazienda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usersazienda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assegnato_Cantiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabile', models.BooleanField(default=False)),
                ('ore_lavorate', models.FloatField(blank=True, null=True)),
                ('cantiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantiere_assegnato', to='home.cantiere')),
                ('personale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personale_assegnato', to='home.personale')),
            ],
            options={
                'db_table': 'assegnato_cantiere',
                'managed': True,
                'unique_together': {('personale', 'cantiere')},
            },
        ),
    ]
